/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralWizardForm.java
 *
 * Created on 30-Jun-2010, 12:25:24
 */

package md.shaman.forms.wizard;

import md.shaman.protocols.Protocol;

/**
 *
 * @author AlexandruC
 */
public class GeneralWizardPanel extends javax.swing.JPanel {

    /** Creates new form GeneralWizardForm */
    public GeneralWizardPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protocolTypeLabel = new javax.swing.JLabel();
        protocolTypeComboBox = new javax.swing.JComboBox();
        sendReceiveLabel = new javax.swing.JLabel();
        sendReceiveComboBox = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        protocolTypeLabel.setLabelFor(protocolTypeComboBox);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(md.shaman.TrafficGeneratorApp.class).getContext().getResourceMap(GeneralWizardPanel.class);
        protocolTypeLabel.setText(resourceMap.getString("protocolTypeLabel.text")); // NOI18N
        protocolTypeLabel.setName("protocolTypeLabel"); // NOI18N

        for(Protocol.ProtocolType s : Protocol.ProtocolType.values())
        protocolTypeComboBox.addItem(s.toString());
        protocolTypeComboBox.setName("protocolTypeComboBox"); // NOI18N

        sendReceiveLabel.setLabelFor(sendReceiveLabel);
        sendReceiveLabel.setText(resourceMap.getString("sendReceiveLabel.text")); // NOI18N
        sendReceiveLabel.setName("sendReceiveLabel"); // NOI18N

        sendReceiveComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Send", "Receive" }));
        sendReceiveComboBox.setName("sendReceiveComboBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendReceiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendReceiveComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(protocolTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(protocolTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocolTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(protocolTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendReceiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendReceiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox protocolTypeComboBox;
    private javax.swing.JLabel protocolTypeLabel;
    private javax.swing.JComboBox sendReceiveComboBox;
    private javax.swing.JLabel sendReceiveLabel;
    // End of variables declaration//GEN-END:variables

}
